# @package _global_

defaults:

  # common params of logging & metrics & train val settings
  - exp/blockworld/block-ssm/train/base


dataset:
  max_frames: 140
  n_frames: 200

  latent:
    type: online

experiment:
  devices: 2
  training:
    batch_size: 16

    splits_included: ['tex_training']

  validation:
    batch_size: 8

    splits_included: ['tex_validation']
    val_every_n_step: 2500


algorithm:
  vae:
    pretrained_path: ${algorithm.vae.pretrained_dir.blockworld_tex}
