
# @package _global_

defaults:
  - /shortcode/exp/common

  # model config such as size and inference params
  - /shortcode/exp/blockworld/dfot/base

  - /shortcode/model_config/cogv/100m

  - override /algorithm/vae: mae_vae_blockworld


algorithm:
  backbone:
    forward_window_size: 140

  tasks:
    prediction:
      context_frames: 50
      history_guidance:
        sliding_context_len: 50
    reconstruction: # Only do prediction for these val samples
      enabled: false
      
  logging:
    max_num_videos: 8
    metrics:
    - fvd
    - lpips
    - mse
    - psnr
    - ssim

dataset:
  max_frames: 200
  num_default_clips: 1000

experiment:
  tasks: ['validation']
  devices: "auto"

  validation:
    batch_size: 32
    precision: 32
    dataloader:
      num_workers: 4
      shuffle: false
    splits_included: ['dynamic_validation_smallworld_no_em_200']
    # Means actually do sampling
    sample_during_training: true


